[build]
target = "x86_64-unknown-uefi"
rustflags = ["-C", "link-args=/subsystem:efi_boot_service_driver"]

[profile.release]
opt-level = "z"
debug = false
strip = "none"
debug-assertions = false
overflow-checks = true
lto = true
panic = "unwind"
incremental = false