#!/bin/bash

RT=$(realpath $(dirname $0))
PARTITION_PARAMS="NAME,MOUNTPOINT,PARTN"
shopt -s extglob

IFS="¬"
for PARTITION_DATA in $(lsblk -o $PARTITION_PARAMS --pairs | awk '{print "¬"$0}'); do
  eval $PARTITION_DATA
done

case "$(uname -s)" in
  "Linux")
    LINUX_NAME=$(lsb_release -ds | tr -d '"')
    KERNEL_VERSION=$(uname -r)
    echo "($LINUX_NAME:$KERNEL_VERSION)"
    ;;
  
  "Darwin")
    MACOS_VERSION=$(sw_vers -productVersion)
    echo "(macOS:$MACOS_VERSION)"
    ;;
  
  *)
    # Unknown platform
    echo "($(uname -s))"
    ;;
esac